version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command:
            echo "Hello, World!"
  unit-test:
    executor:
      name: android/android-machine
      resource-class: medium
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command:
            sh ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save test results
          command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit


workflows:
  test-and-build:
    jobs:
      - unit-test
      - say-hello